### ISSUE TITLE
[1.0] Puppet Lint and document symbol sometimes not working.

### ISSUE THREAD

**Issue by glennsarti** [puppetlabs/puppet-editor-services#272]
During my manual testing I had the following errors appear in the log

```
h":">","options":{"tabSize":2,"insertSpaces":true}}}
---
D, [2020-07-18T20:09:24.655781 #9732] DEBUG -- : --- OUTBOUND
{"jsonrpc":"2.0","id":93,"result":[]}
---
D, [2020-07-18T20:09:24.660598 #9732] DEBUG -- : --- INBOUND
{"jsonrpc":"2.0","id":94,"method":"textDocument/completion","params":{"textDocument":{"uri":"file:///c%3A/Source/example-control-repo/dist/bind/manifests/zone.pp"},"position":{"line":110,"character":17},"context":{"triggerKind":2,"triggerCharacter":">"}}}
---
D, [2020-07-18T20:09:24.663709 #9732] DEBUG -- : --- OUTBOUND
{"jsonrpc":"2.0","id":94,"result":{"items":[],"isIncomplete":false}}
---
E, [2020-07-18T20:09:24.664545 #9732] ERROR -- : PuppetLanguageServer::GlobalQueues::ValidationQueue Thread: Error running job file:///c%3A/Source/example-control-repo/dist/bind/manifests/zone.pp. C:\Source\example-control-repo\dist\bind\manifests\zone.pp

invalid option: --no-trailing_comma-check
["C:/Source/puppet-editor-services/vendor/puppet-lint/lib/puppet-lint/optparser.rb:142:in `build'", "C:/Source/puppet-editor-services/lib/puppet-languageserver/manifest/validation_provider.rb:48:in `block in validate'", "C:/Source/puppet-editor-services/lib/puppet-languageserver/manifest/validation_provider.rb:48:in `chdir'", "C:/Source/puppet-editor-services/lib/puppet-languageserver/manifest/validation_provider.rb:48:in `validate'", "C:/Source/puppet-editor-services/lib/puppet-languageserver/global_queues/validation_queue.rb:54:in `execute_job'", "C:/Source/puppet-editor-services/lib/puppet-languageserver/global_queues/single_instance_queue.rb:118:in `block in thread_worker'", "C:/Source/puppet-editor-services/lib/puppet-languageserver/global_queues/single_instance_queue.rb:108:in `loop'", "C:/Source/puppet-editor-services/lib/puppet-languageserver/global_queues/single_instance_queue.rb:108:in `thread_worker'", "C:/Source/puppet-editor-services/lib/puppet-languageserver/global_queues/single_instance_queue.rb:63:in `block (2 levels) in enqueue_job'"]
D, [2020-07-18T20:09:24.993624 #9732] DEBUG -- : --- INBOUND
{"jsonrpc":"2.0","id":95,"method":"textDocument/documentSymbol","params":{"textDocument":{"uri":"file:///c%3A/Source/example-control-repo/dist/bind/manifests/zone.pp"}}}
---
E, [2020-07-18T20:09:24.997332 #9732] ERROR -- : (textDocument/documentSymbol) undefined method `[]' for #<LSP::DocumentSymbol:0x0000000007774550>
D, [2020-07-18T20:09:24.997568 #9732] DEBUG -- : --- OUTBOUND
{"jsonrpc":"2.0","id":95,"result":null}
```

Both the document symbol provider and puppet lint errors were not working.

**Comment by glennsarti** [comment]
Fixed in #273
